resources:
  repositories:
    - repository: RushstackMainRepo
      type: github
      name: Microsoft/rushstack
      endpoint: 'GitHub (Rushbot)'

pool:
  vmImage: 'ubuntu-latest'
variables:
  NodeVersion: 14
  FORCE_COLOR: 1
steps:
  - checkout: self
    persistCredentials: true
    path: rushstack-legacy
  - template: templates/build.yaml
  - template: templates/publish.yaml
    parameters:
      VersionPolicyName: noRush
  - template: templates/record-published-versions.yaml
